### ISSUE TITLE
cannot find compiled sqlite-vec (breaking change betseen 0.1.2-alpha.9 and 0.1.2-alpha.10)

### ISSUE THREAD

**Issue by tobowers** [asg017/sqlite-vec#107]
minimal failing code: https://github.com/tobowers/minimal-failing-sql-vec-nextjs (ignore the nextjs name there, that's my previous example).

When running 0.1.2-alpha.9 the code works great, but when upping to 0.1.2-alpha.10 (or later) the code fails with the below:

tests/works.spec.ts:
43 |     "..",
44 |     packageName,
45 |     `${ENTRYPOINT_BASE_NAME}.${extensionSuffix(platform)}`
46 |   );
47 |   if (!statSync(loadablePath, { throwIfNoEntry: false })) {
48 |     throw new Error(extensionNotFoundErrorMessage(packageName));
               ^
error: Loadble extension for sqlite-vec not found. Was the sqlite-vec-darwin-arm64 package installed?
      at getLoadablePath (/Users/tobowers/code/minimal-vec-failure/node_modules/sqlite-vec/index.mjs:48:11)
      at load (/Users/tobowers/code/minimal-vec-failure/node_modules/sqlite-vec/index.mjs:55:20)
      at getDatabase (/Users/tobowers/code/minimal-vec-failure/index.ts:11:13)
      at /Users/tobowers/code/minimal-vec-failure/tests/works.spec.ts:6:16
✗ sqlite-vec > should work [1.23ms]

Environment:
MacOs
Bun version: 1.1.28

Seems related to #45 as well.

**Comment by asg017** [comment]
Can confirm this is a bug, looking into a fix now, thanks for reporting!

**Comment by asg017** [comment]
@tobowers can you try with `sqlite-vec@0.1.3-alpha.2` and let me know if it works? I tried it manually on my side and it seems to have fixed it. 

Problem was introduced with some changes I made to the packaging workflow, which incorrectly combined different platform packages (windows library was included in the macos npm package, etc.). Though the latest release should have fixed it. 

Will release a stable `sqlite-vec@0.1.3` once I confirm it all works, apologies again for bug. And thanks a ton for reporting so quickly!

**Comment by tobowers** [comment]
fixed it for me!
