### ISSUE TITLE
bun:sqlite failure due to "does not support dynamic extension loading"

### ISSUE THREAD

**Issue by tobowers** [asg017/sqlite-vec#78]
```ts
   const db = new Database(':memory:');

    sqliteVec.load(db);
    const { vec_version } = db.prepare("select vec_version() as vec_version;").get();
    console.log(`vec_version=${vec_version}`);
```

```
50 | 
51 |   return loadablePath;
52 | }
53 | 
54 | function load(db) {
55 |   db.loadExtension(getLoadablePath());
          ^
error: This build of sqlite3 does not support dynamic extension loading
      at load (/Users/tobowers/code/store-2/node_modules/sqlite-vec/index.mjs:55:6)
      at new EntityStore (/Users/tobowers/code/store-2/src/store.ts:12:15)
      at /Users/tobowers/code/store-2/tests/store.spec.ts:26:13
```

**Comment by tobowers** [comment]
bun version 1.1.22

**Comment by asg017** [comment]
Try configuring bun to use homebrew's SQLite library instead of the builtin MacOS version, like so:

```ts
import { Database } from "bun:sqlite";
import * as sqliteVec from "sqlite-vec";

// MacOS *might* have to do this, as the builtin SQLite library on MacOS doesn't allow extensions
Database.setCustomSQLite("/usr/local/opt/sqlite3/lib/libsqlite3.dylib");

const db = new Database(":memory:");
sqliteVec.load(db);

const embedding = new Float32Array([0.1, 0.2, 0.3, 0.4]);
const { result } = db
  .prepare("select vec_length(?)",)
  .get(embedding);

console.log(result); // 4
```

Checkout the [Bun docs for `setCustomSQLite`](https://bun.sh/docs/api/sqlite#loadextension), and [Bun with `sqlite-vec`](https://alexgarcia.xyz/sqlite-vec/js.html#bun) docs for more info

**Comment by tobowers** [comment]
Thank you! I'll close this now. I will say that doing a `brew install sqlite` did not drop a libsqlite3.dylib in that location and I ended up having to do `/opt/homebrew/Cellar/sqlite/3.46.0/lib/libsqlite3.dylib` which took me a bit to find :).
